#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : nvme-cli
Version  : 1.8.1
Release  : 16
URL      : https://github.com/linux-nvme/nvme-cli/archive/v1.8.1/nvme-cli-1.8.1.tar.gz
Source0  : https://github.com/linux-nvme/nvme-cli/archive/v1.8.1/nvme-cli-1.8.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: nvme-cli-bin = %{version}-%{release}
Requires: nvme-cli-data = %{version}-%{release}
Requires: nvme-cli-license = %{version}-%{release}
Requires: nvme-cli-man = %{version}-%{release}
Patch1: build.patch

%description
Kelly Kaoudis, kelly.n.kaoudis at intel.com, June 2015
Setting Up NVMe Tab Autocompletion for bash or zsh
==================================================

%package bin
Summary: bin components for the nvme-cli package.
Group: Binaries
Requires: nvme-cli-data = %{version}-%{release}
Requires: nvme-cli-license = %{version}-%{release}

%description bin
bin components for the nvme-cli package.


%package data
Summary: data components for the nvme-cli package.
Group: Data

%description data
data components for the nvme-cli package.


%package license
Summary: license components for the nvme-cli package.
Group: Default

%description license
license components for the nvme-cli package.


%package man
Summary: man components for the nvme-cli package.
Group: Default

%description man
man components for the nvme-cli package.


%prep
%setup -q -n nvme-cli-1.8.1
cd %{_builddir}/nvme-cli-1.8.1
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604606322
unset LD_AS_NEEDED
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1604606322
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/nvme-cli
cp %{_builddir}/nvme-cli-1.8.1/LICENSE %{buildroot}/usr/share/package-licenses/nvme-cli/23a1f87d806ce0330b3d85485e399a5f9f553409
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/nvme

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/nvme
/usr/share/zsh/site-functions/_nvme

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/nvme-cli/23a1f87d806ce0330b3d85485e399a5f9f553409

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/nvme-admin-passthru.1
/usr/share/man/man1/nvme-ana-log.1
/usr/share/man/man1/nvme-attach-ns.1
/usr/share/man/man1/nvme-changed-ns-list-log.1
/usr/share/man/man1/nvme-compare.1
/usr/share/man/man1/nvme-connect-all.1
/usr/share/man/man1/nvme-connect.1
/usr/share/man/man1/nvme-create-ns.1
/usr/share/man/man1/nvme-delete-ns.1
/usr/share/man/man1/nvme-detach-ns.1
/usr/share/man/man1/nvme-device-self-test.1
/usr/share/man/man1/nvme-dir-receive.1
/usr/share/man/man1/nvme-dir-send.1
/usr/share/man/man1/nvme-disconnect-all.1
/usr/share/man/man1/nvme-disconnect.1
/usr/share/man/man1/nvme-discover.1
/usr/share/man/man1/nvme-dsm.1
/usr/share/man/man1/nvme-effects-log.1
/usr/share/man/man1/nvme-endurance-log.1
/usr/share/man/man1/nvme-error-log.1
/usr/share/man/man1/nvme-flush.1
/usr/share/man/man1/nvme-format.1
/usr/share/man/man1/nvme-fw-commit.1
/usr/share/man/man1/nvme-fw-download.1
/usr/share/man/man1/nvme-fw-log.1
/usr/share/man/man1/nvme-gen-hostnqn.1
/usr/share/man/man1/nvme-get-feature.1
/usr/share/man/man1/nvme-get-log.1
/usr/share/man/man1/nvme-get-ns-id.1
/usr/share/man/man1/nvme-get-property.1
/usr/share/man/man1/nvme-help.1
/usr/share/man/man1/nvme-huawei-id-ctrl.1
/usr/share/man/man1/nvme-huawei-list.1
/usr/share/man/man1/nvme-id-ctrl.1
/usr/share/man/man1/nvme-id-ns.1
/usr/share/man/man1/nvme-id-nvmset.1
/usr/share/man/man1/nvme-intel-id-ctrl.1
/usr/share/man/man1/nvme-intel-internal-log.1
/usr/share/man/man1/nvme-intel-lat-stats.1
/usr/share/man/man1/nvme-intel-market-name.1
/usr/share/man/man1/nvme-intel-smart-log-add.1
/usr/share/man/man1/nvme-intel-temp-stats.1
/usr/share/man/man1/nvme-io-passthru.1
/usr/share/man/man1/nvme-list-ctrl.1
/usr/share/man/man1/nvme-list-ns.1
/usr/share/man/man1/nvme-list-subsys.1
/usr/share/man/man1/nvme-list.1
/usr/share/man/man1/nvme-lnvm-create.1
/usr/share/man/man1/nvme-lnvm-diag-bbtbl.1
/usr/share/man/man1/nvme-lnvm-diag-set-bbtbl.1
/usr/share/man/man1/nvme-lnvm-factory.1
/usr/share/man/man1/nvme-lnvm-id-ns.1
/usr/share/man/man1/nvme-lnvm-info.1
/usr/share/man/man1/nvme-lnvm-init.1
/usr/share/man/man1/nvme-lnvm-list.1
/usr/share/man/man1/nvme-lnvm-remove.1
/usr/share/man/man1/nvme-netapp-ontapdevices.1
/usr/share/man/man1/nvme-netapp-smdevices.1
/usr/share/man/man1/nvme-ns-descs.1
/usr/share/man/man1/nvme-ns-rescan.1
/usr/share/man/man1/nvme-read.1
/usr/share/man/man1/nvme-reset.1
/usr/share/man/man1/nvme-resv-acquire.1
/usr/share/man/man1/nvme-resv-register.1
/usr/share/man/man1/nvme-resv-release.1
/usr/share/man/man1/nvme-resv-report.1
/usr/share/man/man1/nvme-sanitize-log.1
/usr/share/man/man1/nvme-sanitize.1
/usr/share/man/man1/nvme-security-recv.1
/usr/share/man/man1/nvme-security-send.1
/usr/share/man/man1/nvme-self-test-log.1
/usr/share/man/man1/nvme-set-feature.1
/usr/share/man/man1/nvme-set-property.1
/usr/share/man/man1/nvme-show-regs.1
/usr/share/man/man1/nvme-smart-log.1
/usr/share/man/man1/nvme-subsystem-reset.1
/usr/share/man/man1/nvme-telemetry-log.1
/usr/share/man/man1/nvme-toshiba-clear-pcie-correctable-errors.1
/usr/share/man/man1/nvme-toshiba-vs-internal-log.1
/usr/share/man/man1/nvme-toshiba-vs-smart-add-log.1
/usr/share/man/man1/nvme-wdc-cap-diag.1
/usr/share/man/man1/nvme-wdc-clear-assert-dump.1
/usr/share/man/man1/nvme-wdc-clear-pcie-correctable-errors.1
/usr/share/man/man1/nvme-wdc-drive-essentials.1
/usr/share/man/man1/nvme-wdc-drive-log.1
/usr/share/man/man1/nvme-wdc-drive-resize.1
/usr/share/man/man1/nvme-wdc-get-crash-dump.1
/usr/share/man/man1/nvme-wdc-get-drive-status.1
/usr/share/man/man1/nvme-wdc-get-pfail-dump.1
/usr/share/man/man1/nvme-wdc-id-ctrl.1
/usr/share/man/man1/nvme-wdc-purge-monitor.1
/usr/share/man/man1/nvme-wdc-purge.1
/usr/share/man/man1/nvme-wdc-vs-internal-log.1
/usr/share/man/man1/nvme-wdc-vs-nand-stats.1
/usr/share/man/man1/nvme-wdc-vs-smart-add-log.1
/usr/share/man/man1/nvme-write-uncor.1
/usr/share/man/man1/nvme-write-zeroes.1
/usr/share/man/man1/nvme-write.1
/usr/share/man/man1/nvme.1
